# Generated by Django 4.2.29 on 2026-03-05 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('CodigoLicitacion', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Numero', models.CharField(blank=True, max_length=255, null=True)),
                ('Nombre', models.TextField(blank=True, null=True)),
                ('CodigoEstado', models.IntegerField(blank=True, null=True)),
                ('Estado', models.CharField(blank=True, max_length=255, null=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('Tipo', models.CharField(blank=True, max_length=255, null=True)),
                ('CodigoTipo', models.IntegerField(blank=True, null=True)),
                ('Etapas', models.IntegerField(blank=True, null=True)),
                ('EstadoEtapas', models.CharField(blank=True, max_length=255, null=True)),
                ('C_CodigoOrganismo', models.CharField(blank=True, max_length=255, null=True)),
                ('C_NombreOrganismo', models.CharField(blank=True, max_length=255, null=True)),
                ('C_RutUnidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_CodigoUnidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_DireccionUnidad', models.TextField(blank=True, null=True)),
                ('C_ComunaUnidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_RegionUnidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_RutUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('C_CodigoUsuario', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Usuario', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('FechaCierre', models.DateTimeField(blank=True, null=True)),
                ('FechaInicio', models.DateTimeField(blank=True, null=True)),
                ('FechaFinal', models.DateTimeField(blank=True, null=True)),
                ('FechaPublicacion', models.DateTimeField(blank=True, null=True)),
                ('FechaAdjudicacion', models.DateTimeField(blank=True, null=True)),
                ('FechaEstimadaAdjudicacion', models.DateTimeField(blank=True, null=True)),
                ('Moneda', models.CharField(blank=True, max_length=50, null=True)),
                ('MontoEstimado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('FuenteFinanciamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('TiempoDuracionContrato', models.IntegerField(blank=True, null=True)),
                ('UnidadTiempoDuracion', models.IntegerField(blank=True, null=True)),
                ('TipoDuracionContrato', models.CharField(blank=True, max_length=255, null=True)),
                ('EsRenovable', models.BooleanField(default=False)),
                ('ValorTiempoRenovacion', models.IntegerField(blank=True, null=True)),
                ('PeriodoTiempoRenovacion', models.CharField(blank=True, max_length=255, null=True)),
                ('Adj_Tipo', models.IntegerField(blank=True, null=True)),
                ('Adj_Fecha', models.DateTimeField(blank=True, null=True)),
                ('Adj_Numero', models.CharField(blank=True, max_length=255, null=True)),
                ('Adj_NumeroOferentes', models.IntegerField(blank=True, null=True)),
                ('Adj_UrlActa', models.URLField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleLicitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correlativo', models.IntegerField(blank=True, null=True)),
                ('CodigoProducto', models.CharField(blank=True, max_length=255, null=True)),
                ('CodigoCategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('Categoria', models.TextField(blank=True, null=True)),
                ('NombreProducto', models.TextField(blank=True, null=True)),
                ('DescripcionItem', models.TextField(blank=True, null=True)),
                ('UnidadMedida', models.CharField(blank=True, max_length=255, null=True)),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('RutGanador', models.CharField(blank=True, max_length=255, null=True)),
                ('NombreGanador', models.CharField(blank=True, max_length=255, null=True)),
                ('MontoUnitarioGanador', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CantidadAdjudicada', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CodigoLicitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.licitacion')),
            ],
        ),
    ]
