# Generated by Django 4.2.17 on 2026-03-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devengo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ue', models.CharField(max_length=255, verbose_name='Código Unidad Ejecutora')),
                ('folio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('tipo_presupuesto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Presupuesto')),
                ('moneda_presupuestaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneda Presupuestaria')),
                ('principal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Principal (Proveedor)')),
                ('principal_relacionado', models.CharField(blank=True, max_length=500, null=True, verbose_name='Principal Relacionado')),
                ('moneda_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneda Documento')),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Tipo Cambio')),
                ('tipo_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número Documento')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha Documento')),
                ('fecha_conforme', models.DateField(blank=True, null=True, verbose_name='Fecha Conforme')),
                ('id_chile_compra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id Chile Compra')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso/Recepción')),
                ('catalogo_01', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 01')),
                ('catalogo_02', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 02')),
                ('catalogo_03', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 03')),
                ('catalogo_04', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 04')),
                ('catalogo_05', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 05')),
                ('concepto_presupuestario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Concepto Presupuestario')),
                ('monto_vigente', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Vigente')),
                ('monto_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Disponible')),
                ('monto_consumido', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Consumido')),
                ('archivo_origen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Archivo Origen')),
            ],
            options={
                'verbose_name': 'Devengo',
                'verbose_name_plural': 'Devengos',
                'db_table': 'devengo',
                'ordering': ['-monto_disponible'],
            },
        ),
        migrations.AlterField(
            model_name='detallelicitacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
