# Generated by Django 4.2.17 on 2026-03-11 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devengo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallelicitacion',
            name='CodigoLicitacion',
            field=models.ForeignKey(db_column='CodigoLicitacion_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.licitacion'),
        ),
        migrations.RenameField(
            model_name='detallelicitacion',
            old_name='CodigoLicitacion',
            new_name='licitacion',
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='CodigoLicitacion',
            field=models.CharField(db_column='CodigoLicitacion', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='licitacion',
            old_name='CodigoLicitacion',
            new_name='codigo_licitacion',
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='Numero',
            field=models.CharField(blank=True, db_column='Numero', default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['-monto_disponible'], name='devengo_monto_d_7f75fe_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['codigo_ue'], name='devengo_codigo__1b47c5_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['principal'], name='devengo_princip_215a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['tipo_documento'], name='devengo_tipo_do_e112ab_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['concepto_presupuestario'], name='devengo_concept_26bc60_idx'),
        ),
        migrations.AddIndex(
            model_name='devengo',
            index=models.Index(fields=['codigo_ue', '-monto_disponible'], name='devengo_codigo__ad8489_idx'),
        ),
    ]
