# Generated by Django 4.2.17 on 2026-03-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_detallelicitacion_codigolicitacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('codigo_oc', models.CharField(db_column='CodigoOC', max_length=255, primary_key=True, serialize=False)),
                ('NombreOC', models.TextField(blank=True, null=True)),
                ('CodigoEstado', models.IntegerField(blank=True, null=True)),
                ('EstadoOC', models.CharField(blank=True, max_length=255, null=True)),
                ('CodigoLicitacion', models.CharField(blank=True, max_length=255, null=True)),
                ('TipoOC', models.CharField(blank=True, max_length=255, null=True)),
                ('TipoMoneda', models.CharField(blank=True, max_length=50, null=True)),
                ('Financiamiento', models.CharField(blank=True, max_length=255, null=True)),
                ('FormaPago', models.CharField(blank=True, max_length=255, null=True)),
                ('TipoDespacho', models.CharField(blank=True, max_length=255, null=True)),
                ('Pais', models.CharField(blank=True, max_length=255, null=True)),
                ('FechaCreacion', models.DateTimeField(blank=True, null=True)),
                ('FechaEnvio', models.DateTimeField(blank=True, null=True)),
                ('FechaAceptacion', models.DateTimeField(blank=True, null=True)),
                ('FechaCancelacion', models.DateTimeField(blank=True, null=True)),
                ('FechaUltimaModificacion', models.DateTimeField(blank=True, null=True)),
                ('PromedioCalificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('CantidadEvaluacion', models.IntegerField(blank=True, null=True)),
                ('TotalNeto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('PorcentajeIva', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Impuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('TotalBruto', models.DecimalField(blank=True, db_column='Total', decimal_places=2, max_digits=20, null=True)),
                ('C_CodigoUnidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_RutUnidad', models.CharField(blank=True, max_length=50, null=True)),
                ('C_Actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Direccion', models.TextField(blank=True, null=True)),
                ('C_Comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Region', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('C_Email', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Codigo', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Rut', models.CharField(blank=True, max_length=50, null=True)),
                ('P_Actividad', models.TextField(blank=True, null=True)),
                ('P_Direccion', models.TextField(blank=True, null=True)),
                ('P_Comuna', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Region', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Cargo', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Email', models.CharField(blank=True, max_length=255, null=True)),
                ('DescripcionOC', models.TextField(blank=True, null=True)),
                ('LinkMP', models.URLField(max_length=255, null=True, blank=True)),
                ('ID Proyecto', models.CharField(max_length=255, null=True, blank=True)),
                ('EnlacePAC', models.CharField(max_length=255, null=True, blank=True))
            ],
            options={
                'db_table': 'api_ordencompra',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correlativo', models.IntegerField(blank=True, null=True)),
                ('CodigoCategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('Categoria', models.TextField(blank=True, null=True)),
                ('CodigoProducto', models.CharField(blank=True, max_length=255, null=True)),
                ('Producto', models.TextField(blank=True, null=True)),
                ('EspecificacionComprador', models.TextField(blank=True, null=True)),
                ('EspecificacionProveedor', models.TextField(blank=True, null=True)),
                ('Cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('PrecioNeto', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('TotalImpuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('TotalLinea', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('orden_compra', models.ForeignKey(db_column='CodigoOC_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.ordencompra')),
            ],
            options={
                'db_table': 'api_detalleordencompra',
            },
        ),
    ]
