# Generated by Django 4.2.17 on 2026-03-11 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ordencompra_detalleordencompra'),
    ]

    operations = [
    ]
