# Generated by Django 4.2.17 on 2026-03-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20260311_1518'),
    ]

    operations = [
    ]
