# Generated by Django 4.2.17 on 2026-03-11 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_orden_compra'),
    ]

    operations = [
    ]
