# Generated by Django 4.2.29 on 2026-03-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20260311_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='ID Proyecto',
            field=models.CharField(blank=True, db_column='ID Proyecto', max_length=255, null=True),
        ),
        migrations.RenameField(
            model_name='ordencompra',
            old_name='ID Proyecto',
            new_name='ID_Proyecto',
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='LinkMP',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
