# Generated by Django 4.2.17 on 2026-03-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_ordencompra_id_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('concepto_presupuestario', models.CharField(blank=True, max_length=255, null=True)),
                ('ley_presupuestos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('requerimiento', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('col_4', models.CharField(blank=True, max_length=255, null=True)),
                ('saldo_por_devengar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('deuda_flotante', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ruta_jerarquica', models.TextField(blank=True, null=True)),
                ('establecimiento', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Anexo 1',
                'verbose_name_plural': 'Anexos 1',
                'db_table': 'tabla_anexo1',
            },
        ),
    ]
