# Generated by Django 4.2.17 on 2026-03-12 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_anexo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Comprador',
                'verbose_name_plural': 'Compradores',
                'db_table': 'T_Comprador',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('rut', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre / Razón Social')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'T_Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='BoletaGarantiaAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleta_id', models.IntegerField(verbose_name='ID Boleta eliminada')),
                ('numero_documento', models.CharField(max_length=100, verbose_name='N° Documento')),
                ('snapshot', models.JSONField(verbose_name='Datos al momento de eliminar')),
                ('eliminado_en', models.DateTimeField(auto_now_add=True, verbose_name='Eliminado en')),
                ('razon', models.TextField(blank=True, default='', verbose_name='Razón de eliminación')),
                ('eliminado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por')),
            ],
            options={
                'verbose_name': 'Auditoría Boleta',
                'verbose_name_plural': 'Auditoría Boletas',
                'db_table': 'T_BoletaGarantia_Audit',
                'ordering': ['-eliminado_en'],
            },
        ),
        migrations.CreateModel(
            name='BoletaGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_anio', models.DateField(verbose_name='Mes/Año')),
                ('tipo_documento', models.CharField(choices=[('Boleta De Garantia', 'Boleta De Garantía'), ('Certificado De Fianza', 'Certificado De Fianza'), ('Poliza De Seguro', 'Póliza De Seguro')], max_length=50, verbose_name='Tipo de Documento')),
                ('formato_documento', models.CharField(choices=[('Fisica', 'Física'), ('Electronica', 'Electrónica')], max_length=20, verbose_name='Formato Documento')),
                ('numero_documento', models.CharField(max_length=100, verbose_name='N° Documento')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión de Documento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto')),
                ('banco', models.CharField(choices=[('Banco de Chile', 'Banco de Chile'), ('Santander-Chile', 'Santander-Chile'), ('BCI', 'BCI'), ('Scotiabank', 'Scotiabank'), ('Itau', 'Itau'), ('BICE', 'BICE'), ('Falabella', 'Falabella'), ('Ripley', 'Ripley'), ('Consorcio', 'Consorcio'), ('BTG Pactual', 'BTG Pactual')], max_length=50, verbose_name='Banco')),
                ('id_licitacion', models.CharField(blank=True, default='', max_length=100, verbose_name='ID Licitación')),
                ('nombre_licitacion', models.TextField(blank=True, default='', verbose_name='Nombre Licitación')),
                ('vigencia_garantia', models.DateField(verbose_name='Vigencia de Garantía')),
                ('fecha_derivacion_abastecimiento', models.DateField(blank=True, null=True, verbose_name='Fecha Derivación a Abastecimiento')),
                ('depto_finanzas', models.DateField(blank=True, null=True, verbose_name='Depto. Finanzas')),
                ('numero_memo', models.CharField(blank=True, default='', max_length=100, verbose_name='N° Memo Depto. Abast. Y Op.')),
                ('fecha_despacho_finanzas', models.DateField(blank=True, null=True, verbose_name='Fecha Despacho a Finanzas')),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='boletas/adjuntos/', verbose_name='Archivo Adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletas', to='api.comprador', verbose_name='Comprador')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boletas', to='api.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Boleta de Garantía',
                'verbose_name_plural': 'Boletas de Garantía',
                'db_table': 'T_BoletaGarantia',
                'ordering': ['-vigencia_garantia', '-fecha_emision'],
                'indexes': [models.Index(fields=['-vigencia_garantia'], name='T_BoletaGar_vigenci_7a80df_idx'), models.Index(fields=['-fecha_emision'], name='T_BoletaGar_fecha_e_86738e_idx'), models.Index(fields=['tipo_documento'], name='T_BoletaGar_tipo_do_a62ea1_idx')],
            },
        ),
    ]
