# Generated by Django 4.2.17 on 2026-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_boletas_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletagarantia',
            name='estado_trazabilidad',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Estado Trazabilidad'),
        ),
    ]
