# Generated by Django 4.2.17 on 2026-03-13 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0011_boletagarantia_estado_trazabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='boletagarantiaaudit',
            name='accion',
            field=models.CharField(choices=[('ELIMINAR', 'Eliminación'), ('MODIFICAR', 'Modificación')], default='ELIMINAR', max_length=10, verbose_name='Acción'),
        ),
        migrations.AddField(
            model_name='boletagarantiaaudit',
            name='snapshot_antes',
            field=models.JSONField(blank=True, null=True, verbose_name='Datos antes del cambio'),
        ),
        migrations.AlterField(
            model_name='boletagarantiaaudit',
            name='boleta_id',
            field=models.IntegerField(verbose_name='ID Boleta'),
        ),
        migrations.AlterField(
            model_name='boletagarantiaaudit',
            name='eliminado_en',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha acción'),
        ),
        migrations.AlterField(
            model_name='boletagarantiaaudit',
            name='eliminado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boletas_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='boletagarantiaaudit',
            name='razon',
            field=models.TextField(blank=True, default='', verbose_name='Razón / Observación'),
        ),
        migrations.AlterField(
            model_name='boletagarantiaaudit',
            name='snapshot',
            field=models.JSONField(verbose_name='Datos después del cambio (o al eliminar)'),
        ),
    ]
