# Generated by Django 4.2.17 on 2026-04-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_boleta_audit_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='ID_Proyecto',
            field=models.CharField(blank=True, db_column='ID_Proyecto', max_length=255, null=True),
        ),
    ]
