# Generated by Django 4.2.17 on 2026-04-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_normalize_id_proyecto_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.SmallIntegerField(blank=True, null=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=60, null=True)),
                ('folio', models.BigIntegerField(blank=True, null=True)),
                ('emisor', models.CharField(blank=True, max_length=30, null=True)),
                ('razon_social_emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('receptor', models.CharField(blank=True, max_length=30, null=True)),
                ('publicacion', models.CharField(blank=True, max_length=30, null=True)),
                ('emision', models.CharField(blank=True, max_length=30, null=True)),
                ('monto_neto', models.BigIntegerField(blank=True, null=True)),
                ('monto_exento', models.BigIntegerField(blank=True, null=True)),
                ('monto_iva', models.BigIntegerField(blank=True, null=True)),
                ('monto_total', models.BigIntegerField(blank=True, null=True)),
                ('impuestos', models.TextField(blank=True, null=True)),
                ('estado_acepta', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_sii', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_intercambio', models.CharField(blank=True, max_length=100, null=True)),
                ('informacion_intercambio', models.TextField(blank=True, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('fecha_nar', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_nar', models.CharField(blank=True, max_length=100, null=True)),
                ('uri_nar', models.TextField(blank=True, null=True)),
                ('mensaje_nar', models.TextField(blank=True, null=True)),
                ('uri_arm', models.TextField(blank=True, null=True)),
                ('fecha_arm', models.CharField(blank=True, max_length=30, null=True)),
                ('fmapago', models.CharField(blank=True, max_length=30, null=True)),
                ('dirrecep', models.CharField(blank=True, max_length=200, null=True)),
                ('cmnarecep', models.CharField(blank=True, max_length=200, null=True)),
                ('ciudadrecep', models.CharField(blank=True, max_length=200, null=True)),
                ('controller', models.TextField(blank=True, null=True)),
                ('fecha_vencimiento', models.CharField(blank=True, max_length=30, null=True)),
                ('estado_cesion', models.CharField(blank=True, max_length=100, null=True)),
                ('url_correo_cesion', models.TextField(blank=True, null=True)),
                ('fecha_recepcion_sii', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_reclamo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_reclamo', models.CharField(blank=True, max_length=30, null=True)),
                ('mensaje_reclamo', models.TextField(blank=True, null=True)),
                ('estado_devengo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_devengo', models.CharField(blank=True, max_length=30, null=True)),
                ('folio_oc', models.CharField(blank=True, max_length=60, null=True)),
                ('fecha_ingreso_oc', models.CharField(blank=True, max_length=30, null=True)),
                ('folio_rc', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_ingreso_rc', models.CharField(blank=True, max_length=30, null=True)),
                ('ticket_devengo', models.CharField(blank=True, max_length=30, null=True)),
                ('folio_sigfe', models.CharField(blank=True, max_length=30, null=True)),
                ('tarea_actual', models.CharField(blank=True, max_length=100, null=True)),
                ('area_transaccional', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_aceptacion', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_devengo', models.CharField(blank=True, max_length=30, null=True)),
                ('devengoaut', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_flujo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_revisado', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_usuario_resp', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_usuario_resp', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'data_facturas',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='CodigoCompraAgil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='TipoCompraInterna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
