# Generated by Django 4.2.17 on 2026-05-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_compra_agil_tipo_compra_interna'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='DescripcionDespacho',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='DescripcionFormaPago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='DescripcionMoneda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='DescripcionTipoOC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='TipoOCInterno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
