# Generated by Django 4.2.17 on 2026-05-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_oc_columnas_descriptivas'),
    ]

    operations = [
        migrations.AddField(
            model_name='licitacion',
            name='CantidadReclamos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='CodigoBIP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Contrato',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Contrato_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionAdjTipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionEstimacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionMoneda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionTipoConvocatoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionTipoLicitacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionTipoPago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionUnidadTiempoDuracion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DescripcionUnidadTiempoEval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DiasCierreLicitacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DireccionEntrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='DireccionVisita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='EsBaseTipo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='EsBaseTipo_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='EsRenovable_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='EstadoPublicidadOfertas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Estimacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='ExtensionPlazo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='ExtensionPlazo_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaActoAperturaEconomica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaActoAperturaTecnica',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaEntregaAntecedentes',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaEstimadaFirma',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaInicioContrato',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaPubRespuestas',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaSoporteFisico',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaTiempoEvaluacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='FechaVisitaTerreno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Informada',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Informada_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='JustificacionMonto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='JustificacionPublicidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Modalidad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Obras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Obras_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='ObservacionContract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='ProhibicionContratacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Resp_Contrato',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Resp_Email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Resp_Email_Pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Resp_Fono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Resp_Pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='SubContratacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='SubContratacion_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='Tiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='TipoConvocatoria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='TipoPago',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='TomaRazon',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='TomaRazon_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='UnidadTiempo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='UnidadTiempoContratoLicitacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='UnidadTiempoEvaluacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='VisibilidadMonto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='VisibilidadMonto_Desc',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
