# Generated by Django 4.2.29 on 2026-05-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_ordencompratot_detalleordencompratot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionOCCorregible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_oc', models.CharField(max_length=255)),
                ('revisado_por', models.CharField(max_length=150)),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('Enlazada', 'Enlazada'), ('No Enlazada', 'No Enlazada'), ('Pendiente', 'Pendiente')], max_length=20)),
                ('id_proyecto_asignado', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_no_enlace', models.CharField(blank=True, choices=[('Planificación no informada en el Plan de Compras', 'Planificación no informada en el Plan de Compras'), ('Emergencia o Urgencia Sanitaria Imprevista', 'Emergencia o Urgencia Sanitaria Imprevista'), ('Asignación Extraordinaria de Fondos o Ajuste Presupuestario', 'Asignación Extraordinaria de Fondos o Ajuste Presupuestario'), ('Cambio en las Prioridades del Plan Estratégico Institucional', 'Cambio en las Prioridades del Plan Estratégico Institucional'), ('Quiebre de Stock por Factores de Mercado Externos', 'Quiebre de Stock por Factores de Mercado Externos')], max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'revision_oc_corregible',
                'ordering': ['-fecha_revision'],
            },
        ),
    ]
