# Generated by Django 4.2.17 on 2026-05-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_revision_oc_corregible'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='Nombre_Proyecto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ordencompratot',
            name='Nombre_Proyecto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
