# Generated by Django 4.2.17 on 2026-06-05 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_compraagil_fechas_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionContrato',
            fields=[
                ('numero_contrato', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_contrato', models.TextField(blank=True, null=True)),
                ('id_licitacion_oc', models.CharField(blank=True, max_length=100, null=True)),
                ('rut_organismo', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_organismo', models.TextField(blank=True, null=True)),
                ('ejecucion_contrato', models.CharField(blank=True, max_length=150, null=True)),
                ('categoria_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_contrato', models.CharField(blank=True, max_length=150, null=True)),
                ('unidad_requirente', models.CharField(blank=True, max_length=200, null=True)),
                ('unidad_moneda', models.CharField(blank=True, max_length=20, null=True)),
                ('monto_contrato', models.BigIntegerField(blank=True, null=True)),
                ('monto_ejecutado', models.BigIntegerField(blank=True, null=True)),
                ('monto_por_ejecutar', models.BigIntegerField(blank=True, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_termino', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_contrato', models.CharField(blank=True, max_length=100, null=True)),
                ('garantias_hitos_incumplidos', models.IntegerField(blank=True, null=True)),
                ('garantias_por_vencer', models.IntegerField(blank=True, null=True)),
                ('garantias_vencidas', models.IntegerField(blank=True, null=True)),
                ('garantias_cobradas', models.IntegerField(blank=True, null=True)),
                ('sanciones_solicitadas', models.IntegerField(blank=True, null=True)),
                ('sanciones_aplicadas', models.IntegerField(blank=True, null=True)),
                ('dias_vigencia', models.IntegerField(blank=True, null=True)),
                ('dias_restantes', models.IntegerField(blank=True, null=True)),
                ('evaluacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'data_gestioncontratos',
                'ordering': ['-monto_contrato'],
            },
        ),
    ]
