# Generated by Django 4.2.17 on 2026-06-08 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_add_formularios_fsc'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioFSCEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(db_index=True, max_length=20)),
                ('fecha_registro', models.DateField(db_index=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='api.formulariofsc')),
            ],
            options={
                'db_table': 'data_formularios_fsc_estado_log',
                'ordering': ['formulario_id', 'fecha_registro'],
                'indexes': [models.Index(fields=['formulario', 'fecha_registro'], name='data_formul_formula_180ab0_idx')],
            },
        ),
    ]
