# Generated by Django 4.2.17 on 2026-06-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_add_formularios_fsc_estado_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariofsc',
            name='adj_cotizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofsc',
            name='adj_espec_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofsc',
            name='adj_form_justificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofsc',
            name='adj_validacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofscderivado',
            name='adj_cotizacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofscderivado',
            name='adj_espec_tecnicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofscderivado',
            name='adj_form_justificacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formulariofscderivado',
            name='adj_validacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
