# Generated by Django 4.2.17 on 2026-06-10 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0026_formulariofsc_destino_item_folio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('subdireccion_id', models.IntegerField(blank=True, null=True)),
                ('estado_id', models.IntegerField(blank=True, null=True)),
                ('fecha_mod', models.DateField(blank=True, null=True)),
                ('nombre_corto', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_establecimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('es_depto', models.CharField(blank=True, max_length=5, null=True)),
                ('establecimiento_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'data_departamento',
                'ordering': ['descripcion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('padre_id', models.IntegerField(blank=True, null=True)),
                ('rut', models.IntegerField()),
                ('dv', models.CharField(max_length=1)),
                ('descripcion', models.CharField(max_length=200)),
                ('nombre_corto', models.CharField(blank=True, max_length=50, null=True)),
                ('comuna_id', models.IntegerField(blank=True, null=True)),
                ('estado_id', models.IntegerField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'data_establecimiento',
                'ordering': ['descripcion'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PertenenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('tipo_dependencia', models.CharField(max_length=10)),
                ('id_dependencia', models.IntegerField()),
                ('id_subdireccion', models.IntegerField()),
            ],
            options={
                'db_table': 'data_pertenencia_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.CharField(max_length=1)),
                ('establecimiento_id', models.IntegerField()),
                ('alias', models.CharField(blank=True, max_length=150, null=True)),
                ('run', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'data_usuario_panel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas'), ('viewer', 'Visualizador')], db_index=True, default='viewer', max_length=50)),
                ('panel_id', models.IntegerField(blank=True, null=True)),
                ('establecimiento_id', models.IntegerField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=200, null=True)),
                ('run', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_perfil_usuario',
            },
        ),
    ]
