# Generated by Django 4.2.17 on 2026-06-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_perfil_usuario'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gestioncontrato',
            index=models.Index(fields=['estado_contrato'], name='idx_cont_estado'),
        ),
        migrations.AddIndex(
            model_name='gestioncontrato',
            index=models.Index(fields=['categoria_contrato'], name='idx_cont_categoria'),
        ),
        migrations.AddIndex(
            model_name='gestioncontrato',
            index=models.Index(fields=['unidad_requirente'], name='idx_cont_unidad'),
        ),
        migrations.AddIndex(
            model_name='gestioncontrato',
            index=models.Index(fields=['id_licitacion_oc'], name='idx_cont_licitacion_oc'),
        ),
    ]
