# Generated by Django 4.2.17 on 2026-07-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_perf_indexes_gestioncontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevengoSigfeAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ue', models.CharField(max_length=255, verbose_name='Código Unidad Ejecutora')),
                ('folio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Folio')),
                ('titulo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Título')),
                ('tipo_presupuesto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Presupuesto')),
                ('moneda_presupuestaria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneda Presupuestaria')),
                ('principal', models.CharField(blank=True, max_length=500, null=True, verbose_name='Principal (Proveedor)')),
                ('principal_relacionado', models.CharField(blank=True, max_length=500, null=True, verbose_name='Principal Relacionado')),
                ('moneda_documento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Moneda Documento')),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Tipo Cambio')),
                ('tipo_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número Documento')),
                ('fecha_documento', models.DateField(blank=True, null=True, verbose_name='Fecha Documento')),
                ('fecha_conforme', models.DateField(blank=True, null=True, verbose_name='Fecha Conforme')),
                ('id_chile_compra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Id Chile Compra')),
                ('fecha_emision', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Emisión')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso/Recepción')),
                ('catalogo_01', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 01')),
                ('catalogo_02', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 02')),
                ('catalogo_03', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 03')),
                ('catalogo_04', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 04')),
                ('catalogo_05', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 05')),
                ('catalogo_06', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo 06')),
                ('concepto_presupuestario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Concepto Presupuestario')),
                ('monto_vigente', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Vigente')),
                ('monto_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Disponible')),
                ('monto_consumido', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto Consumido')),
                ('insumo', models.CharField(blank=True, max_length=500, null=True, verbose_name='Insumo')),
                ('monto_vigente_insumo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Monto Vigente Insumo')),
                ('archivo_origen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Archivo Origen')),
                ('row_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Hash de fila')),
                ('fecha_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'Devengo SIGFE Anual',
                'verbose_name_plural': 'Devengos SIGFE Anual',
                'db_table': 'api_sigfe_devengo_anual',
                'ordering': ['-fecha_documento'],
                'indexes': [models.Index(fields=['codigo_ue'], name='api_sigfe_d_codigo__c6a17e_idx'), models.Index(fields=['tipo_documento'], name='api_sigfe_d_tipo_do_cb2abb_idx'), models.Index(fields=['concepto_presupuestario'], name='api_sigfe_d_concept_ab2e17_idx'), models.Index(fields=['fecha_documento'], name='api_sigfe_d_fecha_d_eb9bb0_idx'), models.Index(fields=['codigo_ue', 'fecha_documento'], name='api_sigfe_d_codigo__9ba614_idx')],
            },
        ),
    ]
