# Generated by Django 4.2.17 on 2026-07-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_devengosigfeanual'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoJerarquia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción completa')),
                ('nivel', models.SmallIntegerField(verbose_name='Nivel (1-5)')),
                ('n1_codigo', models.CharField(blank=True, default='', max_length=2, verbose_name='Código N1')),
                ('n1_desc', models.CharField(blank=True, default='', max_length=100, verbose_name='Subtítulo (N1)')),
                ('n2_codigo', models.CharField(blank=True, default='', max_length=4, verbose_name='Código N2')),
                ('n2_desc', models.CharField(blank=True, default='', max_length=100, verbose_name='Ítem (N2)')),
                ('n3_codigo', models.CharField(blank=True, default='', max_length=7, verbose_name='Código N3')),
                ('n3_desc', models.CharField(blank=True, default='', max_length=150, verbose_name='Asignación (N3)')),
                ('n4_codigo', models.CharField(blank=True, default='', max_length=10, verbose_name='Código N4')),
                ('n4_desc', models.CharField(blank=True, default='', max_length=200, verbose_name='Sub-asignación (N4)')),
                ('n5_codigo', models.CharField(blank=True, default='', max_length=12, verbose_name='Código N5')),
                ('n5_desc', models.CharField(blank=True, default='', max_length=255, verbose_name='Detalle (N5)')),
            ],
            options={
                'verbose_name': 'Concepto Presupuestario (Jerarquía)',
                'verbose_name_plural': 'Conceptos Presupuestarios (Jerarquía)',
                'db_table': 'concepto_jerarquia',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['n1_codigo'], name='concepto_je_n1_codi_576c54_idx'), models.Index(fields=['n2_codigo'], name='concepto_je_n2_codi_935983_idx'), models.Index(fields=['n3_codigo'], name='concepto_je_n3_codi_754561_idx')],
            },
        ),
    ]
