# Generated by Django 4.2.17 on 2026-07-15 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_conceptojerarquia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Devengo',
        ),
    ]
