# Generated by Django 4.2.17 on 2026-07-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_delete_devengo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigfeAnexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ue', models.CharField(db_index=True, max_length=20, verbose_name='Código Unidad Ejecutora')),
                ('nombre_establecimiento', models.CharField(max_length=255, verbose_name='Establecimiento')),
                ('anho', models.IntegerField(db_index=True, verbose_name='Año')),
                ('mes', models.IntegerField(db_index=True, verbose_name='Mes (1-12)')),
                ('fecha_desde_tramo', models.DateField(verbose_name='Fecha Desde (tramo descargado)')),
                ('fecha_hasta_tramo', models.DateField(verbose_name='Fecha Hasta (tramo descargado)')),
                ('nivel', models.IntegerField(blank=True, null=True, verbose_name='Nivel')),
                ('concepto_presupuestario', models.CharField(blank=True, max_length=500, null=True, verbose_name='Concepto Presupuestario')),
                ('nivel_cruce', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nivel Cruce')),
                ('catalogo_cruce', models.CharField(blank=True, max_length=500, null=True, verbose_name='Catálogo Cruce')),
                ('ruta_jerarquica', models.TextField(blank=True, null=True, verbose_name='Ruta Jerárquica')),
                ('ley_presupuestos', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('requerimiento', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo_por_aplicar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('compromiso', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo_por_comprometer', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('devengado', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('saldo_por_devengar', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('deuda_flotante', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('archivo_origen', models.CharField(blank=True, max_length=500, null=True, verbose_name='Archivo Origen')),
                ('fecha_sync', models.DateTimeField(auto_now=True, verbose_name='Última sincronización')),
            ],
            options={
                'verbose_name': 'SIGFE Anexo N°1',
                'verbose_name_plural': 'SIGFE Anexo N°1',
                'db_table': 'api_sigfe_anexo1',
                'indexes': [models.Index(fields=['codigo_ue', 'anho', 'mes'], name='idx_sigfe_anexo1_ue_anho_mes')],
            },
        ),
    ]
