# Generated by Django 4.2.17 on 2026-07-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_fix_planerpac_pk_and_new_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacProyectoMaestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(db_index=True, max_length=100)),
                ('nombre_proyecto', models.TextField(blank=True, null=True)),
                ('oc_asociada', models.CharField(blank=True, max_length=100, null=True)),
                ('anho_pac', models.IntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'data_pac_proyecto_maestro',
            },
        ),
    ]
