# Generated by Django 4.2.17 on 2026-07-20 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_pac_proyecto_maestro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SsoSubdireccion',
            fields=[
                ('subdireccion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data_sso_subdireccion',
            },
        ),
        migrations.CreateModel(
            name='SsoDepartamento',
            fields=[
                ('id_dependencia', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre_corto', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('es_depto', models.CharField(blank=True, max_length=5, null=True)),
                ('subdireccion', models.ForeignKey(blank=True, db_column='subdireccion_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departamentos', to='api.ssosubdireccion')),
            ],
            options={
                'db_table': 'data_sso_departamento',
            },
        ),
    ]
