# Generated by Django 4.2.17 on 2026-07-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_sso_jerarquia'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulariofscderivado',
            name='dentro_fuera_pac',
            field=models.CharField(blank=True, choices=[('DENTRO', 'Dentro del PAC'), ('FUERA', 'Fuera del PAC')], db_index=True, help_text='Verificado contra PacProyectoMaestro (id_plan), no contra el campo autodeclarado plan_anual.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='formulariofscderivado',
            name='sso_departamento',
            field=models.ForeignKey(blank=True, help_text='Resuelto por match normalizado de unidad_requirente. Null = "Sin Clasificar".', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_derivados', to='api.ssodepartamento'),
        ),
    ]
