# Generated by Django 4.2.17 on 2026-07-20 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_fsc_derivado_pac_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariofscderivado',
            name='sso_departamento',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Resuelto por match normalizado de unidad_requirente contra Departamento (data_departamento, módulo Usuarios — mejor cobertura que un maestro propio). Null = "Sin Clasificar". db_constraint=False: Departamento es managed=False (tabla externa, id es int(11) vs bigint aquí) — no se fuerza FK física.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios_derivados', to='api.departamento'),
        ),
        migrations.DeleteModel(
            name='SsoDepartamento',
        ),
    ]
