# Generated by Django 4.2.17 on 2026-08-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_fix_sso_departamento_reuse_existente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas'), ('general', 'General (Todos los módulos)'), ('viewer', 'Visualizador')], db_index=True, default='viewer', max_length=50),
        ),
    ]
