# Generated by Django 4.2.17 on 2026-08-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_perfilusuario_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('registros_leidos', models.IntegerField(default=0)),
                ('registros_nuevos', models.IntegerField(default=0)),
                ('registros_actualizados', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('error', 'Error'), ('cancelado', 'Cancelado')], max_length=20)),
                ('error_mensaje', models.TextField(blank=True, null=True)),
                ('usuario', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'data_facturas_sync_log',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
    ]
