# Generated by Django 4.2.17 on 2026-08-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0040_facturas_folio_emisor_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompradorInicial',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Iniciales')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iniciales_comprador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inicial de Comprador',
                'verbose_name_plural': 'Iniciales de Comprador',
                'db_table': 'data_comprador_inicial',
            },
        ),
        migrations.CreateModel(
            name='FscOcLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confianza', models.CharField(choices=[('ALTA', 'Alta — Tipo+Folio+Año+Comprador'), ('MEDIA', 'Media — Tipo+Folio+Año'), ('BAJA_SUGERIDA', 'Baja — solo Tipo+Folio (formato legacy)'), ('MANUAL', 'Manual — enlazado a mano')], db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('SUGERIDO', 'Sugerido'), ('CONFIRMADO', 'Confirmado'), ('RECHAZADO', 'Rechazado')], db_index=True, default='SUGERIDO', max_length=20)),
                ('score_similitud', models.FloatField(blank=True, null=True)),
                ('criterios_match', models.JSONField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('formulario_derivado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces_oc', to='api.formulariofscderivado')),
                ('orden_compra', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='enlaces_fsc', to='api.ordencompra')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enlace FSC-OC',
                'verbose_name_plural': 'Enlaces FSC-OC',
                'db_table': 'data_fsc_oc_link',
                'indexes': [models.Index(fields=['confianza', 'estado'], name='data_fsc_oc_confian_aaaae9_idx'), models.Index(fields=['orden_compra'], name='data_fsc_oc_orden_c_c27307_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='fscoclink',
            constraint=models.UniqueConstraint(fields=('formulario_derivado', 'orden_compra'), name='uniq_fsc_oc_link_par'),
        ),
    ]
