# Generated by Django 4.2.17 on 2026-08-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0041_fsc_oc_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcPacOverride',
            fields=[
                ('orden_compra', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='api.ordencompra')),
                ('id_proyecto_correcto', models.CharField(max_length=100)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('formulario_derivado', models.ForeignKey(blank=True, help_text='FSC desde el cual se hizo la corrección (trazabilidad, opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.formulariofscderivado')),
            ],
            options={
                'verbose_name': 'Corrección PAC de OC',
                'verbose_name_plural': 'Correcciones PAC de OC',
                'db_table': 'data_oc_pac_override',
            },
        ),
    ]
