# Generated by Django 4.2.17 on 2026-09-01 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0042_oc_pac_override'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_proceso', models.CharField(choices=[('LICITACION', 'Licitación'), ('COMPRA_AGIL', 'Compra Ágil'), ('CONVENIO_MARCO', 'Convenio Marco'), ('TRATO_DIRECTO', 'Trato Directo'), ('ORDEN_COMPRA_DIRECTA', 'Orden de Compra Directa')], db_index=True, max_length=25)),
                ('estado_proceso', models.CharField(choices=[('RECEPCIONADO', 'Recepcionado por Comprador'), ('LIC_PUBLICACION', 'Publicación'), ('REVISION_COMPRADOR', 'En Revisión Comprador'), ('LIC_REVISION_BASES_REFERENTE', 'Revisión Bases Referente'), ('LIC_PENDIENTE_AUT_REFERENTE', 'Pendiente Autorización Referente'), ('LIC_PREPARACION_INFORME_EVAL', 'Preparación Informe de Evaluación'), ('LIC_EVALUACION_OFERTAS', 'Evaluación Ofertas'), ('LIC_ADJUDICACION_DESERCION', 'Adjudicación o Deserción'), ('LIC_SEGUNDO_LLAMADO', 'Segundo Llamado'), ('LIC_SUSCRIPCION_CONTRATO', 'Suscripción de Contrato'), ('LIC_EN_EJECUCION', 'En Ejecución'), ('OC_ENVIADA', 'O/C Enviada'), ('CA_PUBLICADA', 'Publicada'), ('CA_ENVIADA_REFERENTE', 'Enviada a Referente'), ('TD_TRAMITACION_RESOLUCION', 'En Tramitación de Resolución que Autoriza'), ('OCD_GESTIONANDO_ENVIO', 'Gestionando el Envío de las Distintas OC'), ('FINALIZADO', 'Proceso Finalizado'), ('OTROS', 'Otros'), ('RECHAZADO', 'Rechazado')], db_index=True, default='RECEPCIONADO', max_length=32)),
                ('titulo', models.CharField(help_text="Identificador corto libre, ej. 'Insumos de Curación 2026'.", max_length=300, verbose_name='Título del proceso')),
                ('codigo_compra_agil', models.CharField(blank=True, db_index=True, help_text='CodigoCompraAgil (api_compraagil_resumen) — sin FK, ver docstring de la clase.', max_length=100, null=True)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('fecha_cierre_estimada', models.DateTimeField(blank=True, help_text='Para alertas de cierre próximo. Se copia desde Licitacion.FechaCierre si hay licitación asociada, o se ingresa a mano para tipos sin registro en MP.', null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('finalizado_en', models.DateTimeField(blank=True, null=True)),
                ('comprador', models.ForeignKey(help_text='Comprador responsable de gestionar el proceso.', on_delete=django.db.models.deletion.PROTECT, related_name='procesos_compra', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesos_compra_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proceso de Compra',
                'verbose_name_plural': 'Procesos de Compra',
                'db_table': 'api_compras_proceso',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas'), ('general', 'General (Todos los módulos)'), ('viewer', 'Visualizador'), ('comprador', 'Comprador'), ('jefatura', 'Jefatura')], db_index=True, default='viewer', max_length=50),
        ),
        migrations.CreateModel(
            name='ProcesoCompraOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('orden_compra', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vinculos_proceso', to='api.ordencompra')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_oc', to='api.procesocompra')),
            ],
            options={
                'db_table': 'api_compras_proceso_oc',
            },
        ),
        migrations.CreateModel(
            name='ProcesoCompraFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('formulario_derivado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_proceso', to='api.formulariofscderivado')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_formulario', to='api.procesocompra')),
            ],
            options={
                'db_table': 'api_compras_proceso_formulario',
            },
        ),
        migrations.CreateModel(
            name='ProcesoCompraEstadoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=32, null=True)),
                ('estado_nuevo', models.CharField(max_length=32)),
                ('comentario', models.TextField(blank=True, default='')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='api.procesocompra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_procesocompra', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_compras_proceso_estado_log',
                'ordering': ['proceso_id', 'fecha'],
            },
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='formularios',
            field=models.ManyToManyField(blank=True, related_name='procesos_compra', through='api.ProcesoCompraFormulario', to='api.formulariofscderivado'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='licitacion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='procesos_compra', to='api.licitacion'),
        ),
        migrations.AddField(
            model_name='procesocompra',
            name='ordenes_compra',
            field=models.ManyToManyField(blank=True, related_name='procesos_compra', through='api.ProcesoCompraOrdenCompra', to='api.ordencompra'),
        ),
        migrations.CreateModel(
            name='ComprasNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMBIO_ESTADO', 'Cambio de Estado'), ('CIERRE_PROXIMO', 'Alerta de Cierre Próximo'), ('NUEVO_PROCESO', 'Nuevo Proceso Creado')], db_index=True, max_length=20)),
                ('mensaje', models.CharField(max_length=500)),
                ('leida', models.BooleanField(db_index=True, default=False)),
                ('email_enviado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_notificaciones', to=settings.AUTH_USER_MODEL)),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='api.procesocompra')),
            ],
            options={
                'db_table': 'api_compras_notificacion',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComprasCompradorPerfil',
            fields=[
                ('nombre_comprador', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='Nombre Comprador (Panel SSO)')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_comprador_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprador (Módulo Compras)',
                'verbose_name_plural': 'Compradores (Módulo Compras)',
                'db_table': 'api_compras_comprador_perfil',
            },
        ),
        migrations.AddConstraint(
            model_name='procesocompraordencompra',
            constraint=models.UniqueConstraint(fields=('proceso', 'orden_compra'), name='uniq_procesocompra_oc'),
        ),
        migrations.AddConstraint(
            model_name='procesocompraformulario',
            constraint=models.UniqueConstraint(fields=('proceso', 'formulario_derivado'), name='uniq_procesocompra_formulario'),
        ),
        migrations.AddIndex(
            model_name='procesocompraestadolog',
            index=models.Index(fields=['proceso', 'fecha'], name='idx_procompra_log_fecha'),
        ),
        migrations.AddIndex(
            model_name='procesocompra',
            index=models.Index(fields=['tipo_proceso', 'estado_proceso'], name='idx_procompra_tipo_estado'),
        ),
        migrations.AddIndex(
            model_name='procesocompra',
            index=models.Index(fields=['comprador', 'estado_proceso'], name='idx_procompra_comprador_estado'),
        ),
        migrations.AddIndex(
            model_name='procesocompra',
            index=models.Index(fields=['fecha_cierre_estimada'], name='idx_procompra_cierre'),
        ),
        migrations.AddIndex(
            model_name='comprasnotificacion',
            index=models.Index(fields=['destinatario', 'leida'], name='idx_compras_notif_dest_leida'),
        ),
    ]
