# Generated by Django 4.2.17 on 2026-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_devengosigfeanual_doc_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fscoclink',
            name='creado_desde_proceso',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
