# Generated by Django 4.2.17 on 2026-10-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_fscoclink_creado_desde_proceso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas'), ('general', 'General (Todos los módulos)'), ('viewer', 'Visualizador'), ('comprador', 'Comprador'), ('jefatura', 'Jefatura Abastecimiento')], db_index=True, default='viewer', max_length=50),
        ),
    ]
