# Generated by Django 4.2.17 on 2026-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_jefatura_abastecimiento_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesocompraformulario',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='procesocompraordencompra',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
