# Generated by Django 4.2.17 on 2026-10-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_compras_indices_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procesocompra',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
