# Generated by Django 4.2.17 on 2026-10-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_procesocompra_indice_creado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasnotificacion',
            name='tipo',
            field=models.CharField(choices=[('CAMBIO_ESTADO', 'Cambio de Estado'), ('CIERRE_PROXIMO', 'Alerta de Cierre Próximo'), ('NUEVO_PROCESO', 'Nuevo Proceso Creado'), ('EMISION_OC', 'Orden de Compra Vinculada')], db_index=True, max_length=20),
        ),
    ]
