# Generated by Django 4.2.17 on 2026-10-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_comprasnotificacion_emision_oc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('abastecimiento', 'Abastecimiento'), ('finanzas', 'Finanzas'), ('general', 'General (Todos los módulos)'), ('viewer', 'Visualizador'), ('comprador', 'Comprador'), ('jefatura', 'Jefatura Abastecimiento'), ('gestor_compras', 'Gestor de Compras')], db_index=True, default='viewer', max_length=50),
        ),
    ]
