# Generated by Django 4.2.17 on 2026-10-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_gestor_compras_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprasnotificacion',
            name='tipo',
            field=models.CharField(choices=[('CAMBIO_ESTADO', 'Cambio de Estado'), ('CIERRE_PROXIMO', 'Alerta de Cierre Próximo'), ('NUEVO_PROCESO', 'Nuevo Proceso Creado'), ('EMISION_OC', 'Orden de Compra Vinculada'), ('FSC_BANDEJA', 'FSC Cambió de Bandeja'), ('FSC_DERIVADO', 'FSC Derivado a Comprador')], db_index=True, max_length=20),
        ),
    ]
