# Generated by Django 4.2.17 on 2026-10-07 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0051_comprasnotificacion_tipos_gestor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacResponsableCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_normalizado', models.CharField(max_length=200, unique=True)),
                ('nombre_original', models.CharField(blank=True, default='', max_length=200)),
                ('correo', models.EmailField(max_length=150)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_pac_responsable_correo',
            },
        ),
        migrations.CreateModel(
            name='NotificacionPlanLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('anho', models.IntegerField(blank=True, null=True)),
                ('modo_prueba', models.BooleanField(db_index=True, default=True)),
                ('estado', models.CharField(choices=[('ENVIANDO', 'Enviando'), ('ENVIADO', 'Enviado'), ('PARCIAL', 'Parcial'), ('ERROR', 'Con error')], default='ENVIANDO', max_length=10)),
                ('filtros', models.TextField(blank=True, default='')),
                ('total_responsables', models.IntegerField(default=0)),
                ('total_planes', models.IntegerField(default=0)),
                ('enviados', models.IntegerField(default=0)),
                ('fallidos', models.IntegerField(default=0)),
                ('resumen_enviado', models.BooleanField(default=False)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_notif_plan_lote',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPlanEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_responsable', models.CharField(max_length=200)),
                ('cargo_responsable', models.CharField(blank=True, default='', max_length=250)),
                ('departamento', models.CharField(blank=True, default='', max_length=250)),
                ('destinatario_real', models.CharField(blank=True, default='', max_length=150)),
                ('enviado_a', models.CharField(blank=True, default='', max_length=500)),
                ('cc', models.TextField(blank=True, default='')),
                ('jefaturas', models.TextField(blank=True, default='')),
                ('asunto', models.CharField(blank=True, default='', max_length=300)),
                ('n_planes', models.IntegerField(default=0)),
                ('monto_total', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ERROR', 'Error')], db_index=True, default='PENDIENTE', max_length=10)),
                ('error', models.TextField(blank=True, default='')),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='api.notificacionplanlote')),
            ],
            options={
                'db_table': 'data_notif_plan_envio',
                'ordering': ['nombre_responsable'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.CharField(db_index=True, max_length=100)),
                ('anho', models.IntegerField(blank=True, null=True)),
                ('nombre_proyecto', models.TextField(blank=True, default='')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.notificacionplanenvio')),
            ],
            options={
                'db_table': 'data_notif_plan_item',
                'indexes': [models.Index(fields=['id_proyecto', 'anho'], name='idx_notif_item_proy_anho')],
            },
        ),
    ]
