# Generated by Django 4.2.17 on 2026-10-07 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0052_notificacion_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionPlanCopia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento_id', models.IntegerField(db_index=True)),
                ('correo', models.EmailField(max_length=150)),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('accion', models.CharField(choices=[('EXCLUIR', 'Excluir de las copias'), ('AGREGAR', 'Agregar a las copias')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_notif_plan_copia',
            },
        ),
        migrations.AddConstraint(
            model_name='notificacionplancopia',
            constraint=models.UniqueConstraint(fields=('departamento_id', 'correo'), name='uq_notif_copia_depto_correo'),
        ),
    ]
